# Generated by Django 2.2.1 on 2019-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190619_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='title',
        ),
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
