# Generated by Django 2.2.1 on 2019-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190620_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='priority',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
